'use client';

import { useState, useEffect } from 'react';

interface GitHubRepo {
  id: number;
  name: string;
  description: string | null;
  stargazers_count: number;
  forks_count: number;
  language: string | null;
  html_url: string;
  private: boolean;
  archived: boolean;
}

export default function Home() {
  const [repositories, setRepositories] = useState<GitHubRepo[]>([]);
  const [selectedRepo, setSelectedRepo] = useState<GitHubRepo | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetchRealRepositories();
  }, []);

  const fetchRealRepositories = async () => {
    try {
      setLoading(true);
      // Fetch repositories from GitHub API
      const response = await fetch('/api/github/repos');
      const data = await response.json();
      
      if (data.success && data.repositories) {
        // Filter out proxy-dealmaker and private repos
        const filteredRepos = data.repositories.filter((repo: GitHubRepo) => 
          repo.name !== 'proxy-dealmaker' && !repo.private && !repo.archived
        );
        
        setRepositories(filteredRepos);
        if (filteredRepos.length > 0) {
          setSelectedRepo(filteredRepos[0]);
        }
      } else {
        setError(data.error || 'Failed to fetch repositories');
        // Fallback to sample data if API fails
        setRepositories(getSampleRepositories());
        setSelectedRepo(getSampleRepositories()[0]);
      }
    } catch (err) {
      console.error('Failed to fetch repositories:', err);
      setError('Network error. Using sample data.');
      // Fallback to sample data
      setRepositories(getSampleRepositories());
      setSelectedRepo(getSampleRepositories()[0]);
    } finally {
      setLoading(false);
    }
  };

  // Sample data as fallback
  const getSampleRepositories = (): GitHubRepo[] => [
    {
      id: 1,
      name: 'bountywarz',
      description: 'Competitive coding platform with real-time AI tournaments',
      stargazers_count: 42,
      forks_count: 18,
      language: 'Python',
      html_url: 'https://github.com/NyxSpecter4/bountywarz',
      private: false,
      archived: false
    },
    {
      id: 2,
      name: 'camel-racing',
      description: '3D racing simulation with blockchain integration',
      stargazers_count: 28,
      forks_count: 9,
      language: 'C#',
      html_url: 'https://github.com/NyxSpecter4/camel-racing',
      private: false,
      archived: false
    }
  ];

  const calculateValuation = (repo: GitHubRepo | null) => {
    if (!repo) return 45000;
    
    // Simple valuation formula based on stars and language
    const baseValue = 25000;
    const starMultiplier = repo.stargazers_count * 500;
    const forkMultiplier = repo.forks_count * 300;
    const languageBonus = repo.language === 'Python' || repo.language === 'TypeScript' ? 10000 : 0;
    
    return baseValue + starMultiplier + forkMultiplier + languageBonus;
  };

  const getStatusColor = (repo: GitHubRepo) => {
    const stars = repo.stargazers_count;
    if (stars > 30) return 'bg-green-500/20 text-green-400';
    if (stars > 15) return 'bg-amber-500/20 text-amber-400';
    return 'bg-gray-500/20 text-silver';
  };

  const getStatusText = (repo: GitHubRepo) => {
    const stars = repo.stargazers_count;
    if (stars > 30) return 'High Demand';
    if (stars > 15) return 'Growing';
    return 'Available';
  };

  return (
    <div className="min-h-screen bg-black text-white overflow-hidden">
      {/* Simple background */}
      <div className="fixed inset-0 z-0 bg-gradient-to-b from-gray-900 to-black"></div>

      <main className="relative z-10">
        {/* Hero */}
        <section className="pt-20 pb-16 px-4">
          <div className="container mx-auto max-w-7xl">
            {/* Logo with 100px spacing */}
            <div className="mb-24 flex flex-col items-center">
              {/* Logo Image - will be generated by scripts/generate-logo.mjs */}
              <div className="mb-8">
                <img
                  src="/logo.png"
                  alt="MAKO THOTH Logo"
                  className="w-[400px] h-auto filter drop-shadow-[0_0_30px_#f59e0b]"
                  onError={(e) => {
                    // If logo doesn't exist yet, show text fallback
                    e.currentTarget.style.display = 'none';
                    const fallback = document.getElementById('logo-fallback');
                    if (fallback) fallback.style.display = 'block';
                  }}
                />
                <div id="logo-fallback" className="hidden">
                  <h1 className="text-6xl md:text-7xl font-black tracking-tighter text-[#f59e0b]">
                    MAKO THOTH
                  </h1>
                </div>
              </div>
              <div className="text-lg text-silver font-serif mt-2">
                SOVEREIGN ASSET VAULT • NYXSPECTER4
              </div>
            </div>

            {/* Sovereign Badge */}
            <div className="max-w-3xl mx-auto mb-12">
              <div className="inline-flex items-center gap-3 px-6 py-3 rounded-full border border-[#F59E0B]/30 bg-black">
                <span className="text-sm font-semibold text-[#F59E0B]">SOVEREIGN ASSET VAULT • OWNER: NYXSPECTER4</span>
              </div>
            </div>

            {/* Asset Selection */}
            <div className="mb-16">
              <h2 className="text-3xl font-bold text-[#F59E0B] mb-8 text-center">SELECT ASSET</h2>
              
              {loading ? (
                <div className="text-center py-12">
                  <div className="inline-block animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-[#F59E0B]"></div>
                  <p className="mt-4 text-silver">Fetching real GitHub repositories...</p>
                </div>
              ) : error ? (
                <div className="text-center py-8">
                  <p className="text-amber-500 mb-4">{error}</p>
                  <p className="text-silver">Showing sample data</p>
                </div>
              ) : repositories.length === 0 ? (
                <div className="text-center py-8">
                  <p className="text-silver">No public repositories found</p>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {repositories.map((repo) => (
                    <button
                      key={repo.id}
                      onClick={() => setSelectedRepo(repo)}
                      className={`text-left p-6 rounded-xl transition-all duration-300 border-2 ${
                        selectedRepo?.id === repo.id
                          ? 'border-[#F59E0B] bg-[#0a0a0f]'
                          : 'border-[#f59e0b] bg-[#0a0a0f] hover:border-[#f59e0b]/80'
                      }`}
                    >
                      <div className="flex justify-between items-start mb-4">
                        <div>
                          <h3 className="text-xl font-bold text-white">{repo.name}</h3>
                        </div>
                        <div className={`px-3 py-1 rounded-full text-xs font-bold ${getStatusColor(repo)}`}>
                          {getStatusText(repo)}
                        </div>
                      </div>
                      
                      <p className="text-silver text-sm mb-4 line-clamp-2">
                        {repo.description || 'No description available'}
                      </p>
                      
                      <div className="flex items-center justify-between mb-4">
                        <div className="flex items-center gap-4">
                          <div className="flex items-center gap-1">
                            <span className="text-sm text-white">⭐ {repo.stargazers_count}</span>
                          </div>
                          <div className="flex items-center gap-1">
                            <span className="text-sm text-white">⑂ {repo.forks_count}</span>
                          </div>
                        </div>
                        {repo.language && (
                          <span className="px-3 py-1 bg-gray-900 rounded-full text-xs text-silver">
                            {repo.language}
                          </span>
                        )}
                      </div>
                      
                      <div className="text-2xl font-black text-[#F59E0B]">
                        ${calculateValuation(repo).toLocaleString()}
                      </div>
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Valuation Results */}
            {selectedRepo && (
              <div className="mb-16 p-8 rounded-3xl border border-[#F59E0B]/20 bg-black">
                <div className="flex justify-between items-center mb-8">
                  <h2 className="text-3xl font-bold text-white">VALUATION BREAKDOWN</h2>
                  <div className="px-4 py-2 bg-[#F59E0B]/20 text-[#F59E0B] rounded-full text-sm font-bold">
                    REAL GITHUB DATA
                  </div>
                </div>

                <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                  <div className="lg:col-span-2">
                    <div className="p-8 rounded-2xl border border-[#F59E0B]/30 bg-gradient-to-r from-black to-gray-900">
                      <div className="text-silver mb-2">AI VALUATION</div>
                      <div className="text-7xl md:text-8xl font-black text-white mb-4">
                        ${calculateValuation(selectedRepo).toLocaleString()}
                      </div>
                      <div className="text-silver">
                        Based on stars, forks, language, and market demand
                      </div>
                      <div className="mt-4 flex items-center gap-4">
                        <div className="px-3 py-1 bg-[#F59E0B]/20 rounded-full text-sm">
                          <span className="text-[#F59E0B]">●</span> {selectedRepo.stargazers_count} Stars
                        </div>
                        <div className="px-3 py-1 bg-[#6366f1]/20 rounded-full text-sm">
                          <span className="text-[#6366f1]">●</span> {selectedRepo.forks_count} Forks
                        </div>
                        <div className="px-3 py-1 bg-[#10b981]/20 rounded-full text-sm">
                          <span className="text-[#10b981]">●</span> {selectedRepo.language || 'Multiple'}
                        </div>
                      </div>
                    </div>

                    <div className="mt-8 p-8 rounded-2xl border-2 border-[#f59e0b] bg-[#0a0a0f]">
                      <div className="flex items-center gap-3 mb-6">
                        <h3 className="text-xl font-bold text-[#F59E0B]">AI INVESTMENT THESIS</h3>
                      </div>
                      <p className="text-white">
                        {selectedRepo.description || 'This repository represents significant technical value.'}
                        With {selectedRepo.stargazers_count} stars and {selectedRepo.forks_count} forks,
                        it demonstrates community engagement and technical sophistication.
                        The {selectedRepo.language || 'primary technology'} stack positions it well for
                        enterprise acquisition or strategic investment.
                      </p>
                    </div>
                  </div>

                  <div className="space-y-6">
                    <div className="p-6 rounded-2xl border border-gray-800 bg-black">
                      <h4 className="font-bold mb-4 text-white">REAL METRICS</h4>
                      <div className="space-y-4">
                        <div className="flex justify-between">
                          <span className="text-silver">GitHub Stars</span>
                          <span className="font-bold text-white">{selectedRepo.stargazers_count}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-silver">Forks</span>
                          <span className="font-bold text-white">{selectedRepo.forks_count}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-silver">Primary Language</span>
                          <span className="font-bold text-white">{selectedRepo.language || 'N/A'}</span>
                        </div>
                        <div className="flex justify-between">
                          <span className="text-silver">Repository</span>
                          <span className="font-bold text-[#F59E0B]">
                            {selectedRepo.name}
                          </span>
                        </div>
                      </div>
                    </div>

                    <div className="p-6 rounded-2xl border border-gray-800 bg-black">
                      <h4 className="font-bold mb-4 text-white">VALUATION COMPONENTS</h4>
                      <div className="space-y-3">
                        <div>
                          <div className="flex justify-between mb-1">
                            <span className="text-sm text-silver">Star Value</span>
                            <span className="text-sm font-bold text-white">${(selectedRepo.stargazers_count * 500).toLocaleString()}</span>
                          </div>
                          <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
                            <div className="h-full bg-[#F59E0B] w-3/4"></div>
                          </div>
                        </div>
                        <div>
                          <div className="flex justify-between mb-1">
                            <span className="text-sm text-silver">Fork Value</span>
                            <span className="text-sm font-bold text-white">${(selectedRepo.forks_count * 300).toLocaleString()}</span>
                          </div>
                          <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
                            <div className="h-full bg-[#6366f1] w-1/2"></div>
                          </div>
                        </div>
                        <div>
                          <div className="flex justify-between mb-1">
                            <span className="text-sm text-silver">Tech Premium</span>
                            <span className="text-sm font-bold text-white">${selectedRepo.language === 'Python' || selectedRepo.language === 'TypeScript' ? '10,000' : '5,000'}</span>
                          </div>
                          <div className="h-2 bg-gray-800 rounded-full overflow-hidden">
                            <div className="h-full bg-[#10b981] w-1/3"></div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Portfolio Summary */}
            <div className="mb-16">
              <h2 className="text-3xl font-bold text-[#F59E0B] mb-8 text-center">PORTFOLIO SUMMARY</h2>
              <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                <div className="p-6 rounded-2xl text-center border border-[#F59E0B]/20 bg-black">
                  <div className="text-4xl font-black text-[#F59E0B] mb-2">
                    ${repositories.reduce((sum, repo) => sum + calculateValuation(repo), 0).toLocaleString()}
                  </div>
                  <div className="text-sm text-silver">Total Portfolio Value</div>
                </div>
                <div className="p-6 rounded-2xl text-center border border-gray-800 bg-black">
                  <div className="text-4xl font-black text-white mb-2">
                    {repositories.length}
                  </div>
                  <div className="text-sm text-silver">Sovereign Assets</div>
                </div>
                <div className="p-6 rounded-2xl text-center border border-gray-800 bg-black">
                  <div className="text-4xl font-black text-white mb-2">
                    {repositories.reduce((sum, repo) => sum + repo.stargazers_count, 0)}
                  </div>
                  <div className="text-sm text-silver">Total GitHub Stars</div>
                </div>
                <div className="p-6 rounded-2xl text-center border border-gray-800 bg-black">
                  <div className="text-4xl font-black text-white mb-2">
                    {repositories.reduce((sum, repo) => sum + repo.forks_count, 0)}
                  </div>
                  <div className="text-sm text-silver">Total Forks</div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Footer */}
        <footer className="border-t border-gray-900 py-8 text-center text-silver text-sm">
          <div className="container mx-auto px-4">
            <p className="text-white font-bold">MAKO THOTH • SOVEREIGN INTELLIGENCE • REAL GITHUB DATA</p>
            <p className="mt-2">Private equity dashboard for NyxSpecter4 software assets • Excludes: proxy-dealmaker</p>
            <p className="mt-1 text-xs text-silver">Data fetched directly from GitHub API</p>
          </div>
        </footer>
      </main>
    </div>
  );
}
